services:
  server:
    build:
      context: .
      target: api
    environment:
      SECRET: ${ALTCHA_SECRET:-$$ecret.key}
      NODE_ENV: production
      CORS_ORIGIN: ${CORS_ORIGIN:-*}
      EXPIREMINUTES: ${EXPIREMINUTES:-10}
      MAXRECORDS: ${MAXRECORDS:-1000}
      MAXNUMBER: ${MAXNUMBER:-5000}
      PORT: ${PORT:-3000}
    ports:
      - "3000:3000"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M

  demo:
    profiles:
      - demo
    build:
      context: .
      target: demo
    environment:
      NODE_ENV: production
      API_BASE_URL: http://server:3000
    depends_on:
      - server
    ports:
      - "8080:8080"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
